[workspace]
resolver = "2"

members = ["aoc-common", "aoc-2023-*"]

[workspace.dependencies]
aoc-common = { path = "./aoc-common" }
clap = { version = "4.4.11", features = ["derive"] }
nom = "7.1.3"

